repos:
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.22.3
    hooks:
      - id: gersemi
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [ --maxkb=500 ]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: fix-byte-order-marker

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
#      - id: clang-tidy
#        args: [-p=build/Debug/compile_commands.json]
#      - id: oclint
#      - id: uncrustify
#      - id: cppcheck
#      - id: cpplint
#      - id: include-what-you-use
